### ISSUE TITLE
All compiler errors have to be fixed before you can enter play mode.

### ISSUE THREAD

**Issue by debuffedhero** [udacity/Introduction-to-Virtual-Reality_Udacity-Carnival#1]
I am brand new to Unity, and in opening this project for the Udacity assignment, I get the message "All compiler errors have to be fixed before you can enter play mode." When I enter the console, I see a list of issues that I have no idea how to reconcile because I'm brand new to the class. I have attached a screenshot.

*UPDATE* Issue resolved- some of the paths were too long for the Windows native decompression to read. I installed WinZip and everything is working fine. Sorry about that! 

![circus error](https://user-images.githubusercontent.com/33443293/41815999-a8b71834-772e-11e8-90c5-19579b0aebd0.JPG)

**Comment by georgezoto** [comment]
Glad you made it work!

**Comment by martinwilter** [comment]
@debuffedhero Thanks for reporting the issue you faced. Glad to hear you were able to resolve it.

For future reference, when using the 'Extract' option in Windows, it will by default extract the content of the zip archive to a folder named the same as the zip archive. So if the zip archive is a compressed folder you will end up with a parent and child folder named the same, for example, extracting `MyZipArchive.zip` will by default create this directory structure:

```
MyZipArchive  <- Created by Windows
    MyZipArchive  <- Compressed folder
        Content of compressed folder
```

To avoid this you can modify the destination folder in the 'Select a Destination and Extract Files' popup that appears when you 'Extract' the content. Or alternatively, navigate inside the zip archive and drag the folder to another location.
